version: '3.3'

services:
  sample-service:
    image: sample-project:latest
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://host.docker.internal:3306/recruitment'
      SPRING_DATASOURCE_USERNAME: 'root'
      SPRING_DATASOURCE_PASSWORD: 'dungprofg123'
      SPRING_JPA_HIBERNATE_DDLAUTO: 'update'
      SPRING_DATA_REDIS_HOST: 'redis'   # Thay đổi host thành tên của service Redis
      SPRING_DATA_REDIS_PORT: '6379'
      SPRING_DATA_REDIS_PASSWORD: ''
    ports:
      - '8088:8088'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: on-failure

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dungprofg123
      MYSQL_DATABASE: recruitment
      MYSQL_USER:
      MYSQL_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db:
    driver: local





